In [1]:
# !/usr/bin/env python
# -*- coding: UTF-8 -*-

In [2]:
import copy
import numpy as np

In [20]:
# 定义4x4网格类,环境
class GridMapEnvironment(object):
    
    def __init__(self):
        # 定义状态、动作、收益的取值范围
        self._states = np.array(range(16))
        self._actions = np.array(['up', 'down', 'left', 'right'])
        self._rewards = np.array([-1, 0])
        
        # 初始化状态
        self._state = 0
        
    # get set 函数，用以访问类内变量
    def getStates(self):
        return self._states
    
    def getActions(self):
        return self._actions
    
    def getRewards(self):
        return self._rewards
    
    def getState(self):
        return self._state
    
    def setState(self, state):
        assert state in self._states
        self._state = state
    
    # 更新 state
    def _updateState(self, act):
        assert act in self._actions
        act_func = getattr(self, '_' + act)
        act_func()
        
    # action 函数，定义动作对 state 的影响
    def _up(self):     
        if self._state in [0, 1, 2, 3, 15]:
            pass
        else:
            self._state = self._state - 4
    
    def _down(self):   
        if self._state in [0, 12, 13, 14, 15]:
            pass
        else:
            self._state = self._state + 4
    
    def _left(self):
        if self._state in [0, 4, 8, 12, 15]:
            pass
        else:
            self._state = self._state - 1
    
    def _right(self):
        if self._state in [0, 3, 7, 11, 15]:
            pass
        else:
            self._state = self._state + 1
            
    def _returnReward(self):
        if self._state in [0, 15]:
            return 0
        else:
            revaluation_result = np.resize(state_value, (4, 4))
print(evaluation_result)eturn -1
    
    def takeAction(self, act):
        r = self._returnReward()
        self._updateState(act)
        return r

In [37]:
# 策略评估测试
# 设置策略评估环境，value 序列，action 概率分布，折扣系数（i.e.超参数）
grid_map = GridMapEnvironment()
state_value = np.zeros(grid_map.getStates().size)
prob_act = 0.25
gamma = 1.0

# 策略评估代码，未进行封装（非优化版本）
for t in range(100):
    # 生成 value 序列 的 copy
    state_value_copy = copy.deepcopy(state_value)
    # 清空 value 序列 以进行下一轮的 policy evaluation 迭代
    state_value = np.zeros(grid_map.getStates().size)
    # 对每一个 state 进行策略评估
    for s in grid_map.getStates():
        for a in (grid_map.getActions()):
            grid_map.setState(s)
            state_value[s] = state_value[s] + prob_act * (grid_map.takeAction(a) + gamma * state_value_copy[grid_map.getState()])
    if t in [0, 1, 2, 9, 99]:
        print('----------------------------------')
        print('policy evaluation result after ' + str(t + 1) + ' times: ')
        print(np.resize(state_value, (4, 4)))

----------------------------------
policy evaluation result after 1 times: 
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
----------------------------------
policy evaluation result after 2 times: 
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
----------------------------------
policy evaluation result after 3 times: 
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
----------------------------------
policy evaluation result after 10 times: 
[[ 0.         -6.13796997 -8.35235596 -8.96731567]
 [-6.13796997 -7.73739624 -8.42782593 -8.35235596]
 [-8.35235596 -8.42782593 -7.73739624 -6.13796997]
 [-8.96731567 -8.35235596 -6.13796997  0.        ]]
----------------------------------
policy evaluation result after 100 times: 
[[  0.         -13.94260509 -19.91495107 -21.90482522]
 [-13.94260509 -17.92507693 -1